#!/bin/bash
linux(){
   if [[ "$(uname -o)" == "GNU/Linux" ]];then
      apt update && apt upgrade && apt install python3.11 && pip3.11 install beautifulsoup4 requests
   else
      clear && exit
   fi
}
termux(){
   if [[ "$(uname -o)" == "Android" ]];then
      pkg update && pkg upgrade && pkg install python && pip install beautifulsoup4 requests
   else
      clear && exit
   fi
}

F="\033[m"
A="\033[01;33m"
VD="\033[01;32m"
clear 
echo -e $A"Qual seu SO?"
echo -e $VD"["$A"1"$VD"]"$A"Linux"
echo -e $VD"["$A"2"$VD"]"$A"Android"
echo -n -e $VD">>>"$F
read op
case $op in
   1)linux;;
   2)termux;;
   *)clear;exit;;
esac
